dist: trusty

language: node_js
node_js:
  - "8"

services:
  - postgresql

cache:
  yarn: true

before_script:
  - psql -c 'create database synergy;' -U postgres

script:
  - cd server
  - yarn install
  - yarn run lint
  - yarn run build
  - yarn run test
